Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using SMSControlPanel.Repository.BusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Serilog;
using SMSControlPanel.Models;
using Microsoft.AspNetCore.Http;
using SMSControlPanel.Repository;
using SMSControlPanel.Service;

namespace SMSControlPanel.Controllers
{
    [RoleAuthorize("SuperAdmin")]
    public class AdminController : Controller
    {
        private readonly IAdminBL _admin;
        private readonly IAuthService _authService;
        public AdminController(IAdminBL admin, IAuthService authService)
        {
            _admin = admin;
            _authService = authService;

        }

        public async Task<IActionResult> ManageUsers()
        {
            var userviewmodel = _authService.GetUserModel();

            ViewBag.UserData = await _admin.LoadUsersData();

            return View(userviewmodel);
        }

        public async Task<JsonResult> LoadUsersData()
        {
            try
            {
                List<AdminModel> userData = await _admin.LoadUsersData();

                return Json(userData);
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }

        }

        //public JsonResult LoadUsersData()
        //{
        //    try
        //    {
        //        List<AdminModel> userData = _admin.LoadUsersData();

        //        //var pagedData = ApplyPagination(userData, data);

        //        //var response = new {
        //        //    Draw = data.Draw,
        //        //    recordsTotal = data.Length,
        //        //    recordsFiltered = userData.Count,
        //        //    data = pagedData
        //        //};

        //        return Json(userData);
        //    }
        //    catch (Exception ex)
        //    {
        //        Log.Logger.Error(ex.Message);
        //        return Json(new { success = false, err = ex.Message });
        //    }

        //}

        //private static dynamic[] ApplyPagination(List<AdminModel> data, DataTableParameters parameters)
        //{
        //    var StartIndex = parameters.Start;
        //    var Length = parameters.Length;

        //    return data.Skip(StartIndex).Take(Length).ToArray();
        //}
        public async Task<JsonResult> SearchFirstLastName(string first, string last)
        {
            try
            {
                List<AdminModel> firstlast = await _admin.SearchFirstLastName(first, last);
                return Json(firstlast);
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> DeleteUser(string empid, string update_by)
        {
            try
            {
                // Delete the user with the specified ID
                var result = await _admin.DeleteUser(empid, update_by);
                return Json(new { success = result });
            }
            catch (Exception ex)  //[SP_VMTP_USER_DELETE]
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> UpdateUser(AdminModel model) {
            try
            {
                var InsertBy = _authService.GetUserModel().EmpID;
                bool result = await _admin.UpdateUser(model,InsertBy);
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> InsertUser(AdminModel model)
        {
            try
            {
                bool IsExist = await _admin.CheckExist(model);
                if (IsExist)
                    return Json(new { success = false });

                var InsertBy = _authService.GetUserModel().EmpID;
                bool result = await _admin.InsertUser(model, InsertBy);
                return Json(new { success = result });
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }

        //[HttpPost]
        //public JsonResult CheckExist(AdminModel model)
        //{
        //    try
        //    {
        //        var InsertBy = GetUserViewModel().User.EmpID;
        //        bool result = _admin.CheckExist(model);
        //        return Json(new { success = true });
        //    }
        //    catch (Exception ex)
        //    {
        //        Log.Logger.Error(ex.Message);
        //        return Json(new { success = false, err = ex.Message });
        //    }
        //}

        [HttpPost]
        public async Task<JsonResult> GetTeamDetails(string DeptID)
        {
            try
            {
                List<TeamTemplateModel> Teams = await _admin.GetTeamDetails(DeptID);

                return Json(Teams);
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);

                return Json(new { success = false, err = ex.Message });
            }
        }

        public async Task<JsonResult> GetRoleDetails()
        {
            try
            {
                List<RoleModel> Roles = await _admin.GetRoles();
                return Json(Roles);
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }   

        [HttpPost]
        public async Task<JsonResult> GetColleagues(string firstname, string lastname)
        {
            try
            {
                List<ColleagueModel> Colleagues = await _admin.GetColleagues(firstname, lastname);
                return Json(Colleagues);

            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }
    }
}

Controllers/ExportController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using Serilog;
using SMSControlPanel.DataLayer;
using SMSControlPanel.Models;
using SMSControlPanel.Repository;
using SMSControlPanel.Repository.BusinessLogic;
using SMSControlPanel.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SMSControlPanel.Controllers
{
    [RoleAuthorize("SuperAdmin")]
    public class ExportController : Controller
    {
        private readonly IGenerateReportBL _report;
        private readonly IAuthService _authService;
        public ExportController( IGenerateReportBL report,IAuthService authService)
        {
            _report = report;
            _authService = authService;
        }
        public IActionResult ExportMonthly()
        {
            var userviewmodel = _authService.GetUserModel();
            return View(userviewmodel);
        }

        public async Task<JsonResult> GetMonths()
        {
            try
            {
                List<string> months = await _report.GetMonth();
                return Json(months);
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> ExcelExport(int Month, int Year)
        {
            try
            {
                string SheetName = "SMS Usage";
                ExcelPackage.LicenseContext = LicenseContext.Commercial;
                ExcelPackage excelPackage = new();

                List<ExcelModel> result = await _report.GetExcelData(Month, Year);

                excelPackage = CommonClass.ListToExcel<ExcelModel>(result,SheetName);

                var stream = new MemoryStream(excelPackage.GetAsByteArray());

                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");

            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }
    }
}

Controllers/MaintainDLController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Serilog;
using SMSControlPanel.DataLayer;
using SMSControlPanel.Models;
using SMSControlPanel.Repository;
using SMSControlPanel.Repository.BusinessLogic;
using SMSControlPanel.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static System.Net.WebRequestMethods;

namespace SMSControlPanel.Controllers
{
    [RoleAuthorize("Admin", "SuperAdmin")]
    public class MaintainDLController : Controller
    {
        private readonly IGetDistListBL _distlist;
        private readonly IHostEnvironment _environment;
        private readonly IAuthService _authService;
        public MaintainDLController(IGetDistListBL distlist, IAuthService authService, IHostEnvironment environment)
        {
            _distlist = distlist;
            _environment = environment;
            _authService = authService;
        }
        public IActionResult DistList()
        {
            var userviewmodel = _authService.GetUserModel();
            return View(userviewmodel);
        }

        public IActionResult CreateDL()
        {
            var userviewmodel = _authService.GetUserModel();
            return View(userviewmodel);
        }

        public IActionResult UpdateDL(string ListName)
        {
            ViewData["ListName"] = ListName;
            var userviewmodel = _authService.GetUserModel();
            return View(userviewmodel);
        }

        public IActionResult ViewDL(string ListName)
        {
            ViewData["ListName"] = ListName;
            var userviewmodel = _authService.GetUserModel();
            return View(userviewmodel);
        }

        public async Task<JsonResult> LoadDL()
        {
            try
            {
                var CompanyID = _authService.GetUserModel().DEPARTMENTID;

                List<DLModel> result = await _distlist.GetDLandEntries(CompanyID);

                return Json(result);

            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> DeleteDL(string ListName)
        {
            try
            {
                var CompanyID = _authService.GetUserModel().DEPARTMENTID;
                bool result = await _distlist.DeleteDL(ListName, CompanyID);

                return Json(result);
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public async Task<JsonResult> CheckExists(string ListName)
        {
            try
            {
                var Company = _authService.GetUserModel().CompanyName;
                bool IsExists = await _distlist.CheckExists(ListName, Company);
                return Json(new { success=IsExists });
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> UploadFile()
        {
            try
            {
                string response = null;

                var username = _authService.GetUserModel().EmpID;
                var company = _authService.GetUserModel().CompanyName;
                var companyID = _authService.GetUserModel().DEPARTMENTID;

                var file = Request.Form.Files[0];
                var listname = Request.Form["text"].ToString();

                string DirectoryPath = _environment.ContentRootPath + @"\Uploads";
                var fileName = file.FileName;
                var filePath = Path.Combine(DirectoryPath, fileName);

                if (!Directory.Exists(DirectoryPath))
                {
                    Directory.CreateDirectory(DirectoryPath);
                }

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);

                    fileStream.Close();
                    fileStream.Dispose();
                }
                    

                if (fileName.EndsWith(".txt", StringComparison.OrdinalIgnoreCase))
                {
                    response = await _distlist.UploadTxtFile(filePath, listname, username, company, companyID);
                }
                else
                {
                    response = await _distlist.UploadCSVFile(filePath, listname, username, company, companyID);
                }

                return Json(response);
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public async Task<JsonResult> GetPhoneNumbers(string ListName)
        {
            try
            {
                var companyID = _authService.GetUserModel().DEPARTMENTID;

                List<string> PhNumbers = await _distlist.GetPhonenumbers(ListName, companyID); //retreiving from query instead of actual SP

                return Json(PhNumbers);

            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }
        
        [HttpPost]
        public async Task<IActionResult> ExportDL()
        {
            try
            {
                string SheetName = "DL List";
                var CompanyID = _authService.GetUserModel().DEPARTMENTID;

                List<DLModel> result = await _distlist.GetDLandEntries(CompanyID);

                var excelPackage = CommonClass.ListToExcel<DLModel>(result,SheetName);

                var stream = new MemoryStream(excelPackage.GetAsByteArray());

                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            }
            catch (Exception ex)
            {
                Log.Logger.Error(ex.Message);
                return Json(new { success = false, err = ex.Message });
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var FirstName = @Model?.FIRSTNAME;
    var LastName = @Model?.LASTNAME;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SMSControlPanel</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="~/css/global/Site.css" rel="stylesheet" />
    <link href="~/css/global/Main.css" rel="stylesheet" />
    <link href="~/css/global/mbTooltip.css" rel="stylesheet" />
    <link href="~/css/global/jqueryslidemenu.css" rel="stylesheet" />
    <link href="~/lib/datatable/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-ui/jquery-ui.min.css" rel="stylesheet" />

    <link href="~/css/global/Layout.css" rel="stylesheet" />


</head>
<body>
    <div class="container" id="dvContent">
        <header>

            <div id="dvheader">
                <table style="width:100%;">
                    <tr>
                        <td style="display:inline-block">
                            <img id="Image2" src="~/images/vm_logo_title.png" alt="logo" style="width:80%" />
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            <label id="LabelUserName">Welcome @FirstName @LastName</label>
                        </td>
                        <td align="right">
                            <span id="clock"></span>
                        </td>
                    </tr>
                </table>
            </div>

            <div id="wrap">
                <ul class="navbar-native">
                    <li id="DvGeneralView" class="arrowlistmenu">
                        <a href="#">Send SMS<span class="arrow"></span></a>
                        <ul>
                            <li><a asp-controller="SendSmsText" asp-action="Index">Send SMS Text</a></li>
                        </ul>
                    </li>
                    <li id="DvReports" class="arrowlistmenu">
                        <a href="#">Distribution List<span class="arrow"></span></a>
                        <ul>
                            <li><a asp-controller="MaintainDL" asp-action="DistList">Maintain DL</a></li>
                            <li><a asp-controller="DistList" asp-action="SendToDL">Send SMS to DL</a></li>
                        </ul>
                    </li>
                    <li id="Div1" class="arrowlistmenu">
                        <a href="#">Reporting<span class="arrow"></span></a>
                        <ul>
                            <li><a asp-controller="GeneralReport" asp-action="Report">General Reports</a></li>
                            <li id="DvExport1"><a asp-controller="Export" asp-action="ExportMonthly">Export Excel</a></li>
                        </ul>
                    </li>
                    <li id="DvAdmin" class="arrowlistmenu">
                        <a href="#">Admin<span class="arrow"></span></a>
                        <ul>
                            <li><a asp-controller="Admin" asp-action="ManageUsers">Manage Users</a></li>
                        </ul>
                    </li>
                    <li id="Li1" class="arrowlistmenu" data-toggle="tooltip" data-placement="top" title="Not Live" style="display:none">
                        <a href="#">Inbox <span class="arrow"></span></a>
                        <ul>
                            <li><a href="#">Messages</a></li>
                            <li><a href="#">Download Messages</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

        </header>

        <main role="main">
            @RenderBody()
        </main>

        <footer>
            <table style="width:100%">
                <tr>
                    <td>
                        <div class="Copyright" style="padding:2px">
                            <span style="font-size: 11px; font-family: Arial; font-weight: bold">
                                Last modified
                                by: Intranet Team 22/06/2016
                            </span>
                        </div>
                    </td>
                </tr>
            </table>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/lib/datatable/datatables.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

    <script src="~/js/global/Layout.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>